### ISSUE TITLE
selinux confinement for precached

### ISSUE THREAD

**Issue by idnovic** [X3n0m0rph59/precached#22]
**This is the selinux development thread.**
_Current test version of the confinement is in [post number 2](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-512982739)._
# 

**State**: non-productive test systems. Many AVC notices. Blacklist needs improvements
The confinement is fully functional at base level. A full test of all precached features is needed.

Every precached binary and folder is part of the confinement. port 8023 is preset as usable for the not currently per default running web server.

Precached is able to load/unload files into memory while in permissive mode.

# 
#### Todo

- [ ] [uncertain](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513003417)
- [ ] [asks for to much](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513239885)
- [ ] [Blacklist](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513240608)
- [x] [missing binaries](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513295551)
- [ ] [optional policy](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513548048)

# 
### Precached Selinux Guide

_change working directory to pkg_precached_selinux_

#### Change on version update
```
precached.te > policy_module(precached, 1.1.1)
precached_selinux.spec > %define selinux_policyver 1.1.1
precached_selinux.spec > Version:        1.1
```
#### **WARNING** deletes and generate new policy, only use for new barebone policy
`$ DIDYOUREADME sudo sepolicy generate --init /usr/sbin/precached`

#### Check syntax, test and build policy
`$ sudo ./precached.sh`

#### Update precached.pp policy
`$ sudo make -f /usr/share/selinux/devel/Makefile precached.pp`

#### Install precached.pp policy (optional)
`$ sudo /usr/sbin/semodule -i precached.pp`

#### Check syntax, test and build policy (optional)
`$ sudo ./precached.sh`

#### Install policy
`$ sudo dnf install ./noarch/precached_selinux-1.1-1.fc30.noarch.rpm`

#### Check for re confinement
`$ ls -Zd /var/lib/precached/ && ls -Zd /usr/sbin/iotracectl`

#### Restart precached service
`$ sudo systemctl restart precached`

#### Check for avc notices
_(cherry pick needed allow rules from the next 2 commands into precached.te per hand)_
```
$ sudo ausearch -c 'precached' --raw | audit2allow -M my-precached
$ sudo ausearch -c 'precached/fanot' --raw | audit2allow -M my-precachedfanot
```

#### Check syntax, test and build policy
`$ sudo ./precached.sh --update`

#
#### Switch to enforcing after the policy reached a stable level
`remove "permissive precached_t;" from precached.te`

#### To avoid issues the domain can be set to permissive at first use
`$ sudo semanage permissive -a precached_t`

#

**Comment by idnovic** [comment]
Above are the once I am uncertain about. I have a longer list with permissions I do not want to give. So we will need to make sure precached ignores certain directories to decrease selinux notifications about blocked access attempts.

**Comment by idnovic** [comment]
8. Does precached require access to locate/mlocate? locate_var_lib_t (/var/lib/[sm]locate(/.*)?)

**Comment by idnovic** [comment]
Current test version of precached_selinux  **1.3-1**
_inside the /noarch directory is the install able rpm file_
_changelog is viewable in the spec file_

**The not yet released version 1.7-X of the selinux confinement should be the stable version for precached 1.7-X series. Version 1.8-X for 1.8-X ... . Versions from 1.1 to 1.6 are unstable development versions for the current precached-git package till a stable version of the confinement is reached.**

**Downloads**
1.3-1 [pkg_precached_selinux.zip](https://github.com/X3n0m0rph59/precached/files/3414542/pkg_precached_selinux.zip)
1.2-1 [pkg_precached_selinux.zip](https://github.com/X3n0m0rph59/precached/files/3411748/pkg_precached_selinux.zip)
1.1-1 [pkg_precached_selinux.zip](https://github.com/X3n0m0rph59/precached/files/3411656/pkg_precached_selinux.zip)

**Comment by idnovic** [comment]
Because precached likes to access every file, selinux does not like precached much. I get many avc notices. I added the allow rules which seemed reasonable. Below are the once I am uncertain about. 

Does precached require access to...
- [ ] 1. ... sysfs interface? sysfs_t
- [ ] 2. ... sudo? sudo_exec_t
- [ ] 3. ... users home direcotory?
- [x] 4. ... DAC? Discretionary Access Control
- [ ] 5. ... auditd? auditd_t
- [x] 6. ... proc? proc_t
- [ ] 7. ... initrc? initrc_var_run_t
- [ ] 8. ... locate/mlocate? locate_var_lib_t (/var/lib/[sm]locate(/.*)?) 
- [ ] 9. ... dbus? unconfined_dbusd_t dbusd_exec_t
- [ ] 10. ... cap_userns? tclass=cap_userns

**Comment by idnovic** [comment]
List of things precached asks for (because it tries to access every file) but I do not want to give:

```
#allow precached_t auditd_t:dir search;
#allow precached_t auditd_t:file { open read };
#allow precached_t auditd_t:lnk_file read;
#allow precached_t cache_home_t:file { open read };
#allow precached_t chkpwd_exec_t:file { open read };
#allow precached_t config_home_t:file { open read };
#allow precached_t data_home_t:file { open read };
#allow precached_t initrc_var_run_t:file { getattr open read };
#allow precached_t locate_var_lib_t:file { open read };
#allow precached_t NetworkManager_exec_t:file getattr;
#allow precached_t NetworkManager_t:dir search;
#allow precached_t NetworkManager_t:file { open read };
#allow precached_t NetworkManager_t:lnk_file read;
#allow precached_t rpm_exec_t:file { open read };
#allow precached_t rpm_var_lib_t:file open;
#allow precached_t semanage_store_t:file { open read };
#allow precached_t setroubleshootd_exec_t:file { getattr open read };
#allow precached_t setroubleshootd_t:dir search;
#allow precached_t setroubleshootd_t:file { open read };
#allow precached_t setroubleshootd_t:lnk_file read;
#allow precached_t setroubleshoot_var_lib_t:file { open read };
#allow precached_t shadow_t:file { open read };
#allow precached_t sudo_exec_t:file { getattr open read };
#allow precached_t sysfs_t:dir read;
#allow precached_t systemd_passwd_agent_exec_t:file getattr;
#allow precached_t systemd_systemctl_exec_t:file { getattr open read };
#allow precached_t user_home_t:file { open read };
```

**Comment by idnovic** [comment]
Paths which need to be hardcoded into a blacklist to decrease the avc notices from selinux for precached:

```
/usr/bin/sudo					sudo_exec_t
/usr/bin/systemd-tty-ask-password-agent		systemd_passwd_agent_exec_t
/etc/shadow					shadow_t
/usr/sbin/unix_chkpwd				chkpwd_exec_t
/usr/libexec/fprintd				fprintd_exec_t
/usr/bin/rpm					rpm_exec_t
/var/lib/rpm/Packages				rpm_var_lib_t
/usr/lib/systemd/systemd			init_exec_t
/usr/lib/systemd/*
/usr/libexec/geoclue				geoclue_exec_t
/home/XXX/.bashrc				user_home_t
/usr/lib/systemd/system/fprintd.service		systemd_unit_file_t
/usr/lib/systemd/*
/home/XXX/.config/dconf/user			config_home_t
/home/XXX/.local/share/gnome-shell/extensions/Vitals@CoreCoding.com/icons/temperature-symbolic.svg
data_home_t
/home/*

/run/utmp					initrc_var_run_t
/etc/NetworkManager/dispatcher.d/99-ddns.sh	NetworkManager_initrc_exec_t
/etc/NetworkManager/*
/usr/sbin/NetworkManager
/usr/libexec/nm-dispatcher
/usr/lib/systemd/system/NetworkManager-dispatcher.service
/usr/sbin/chronyd				chronyd_exec_t
/usr/bin/chronyc
/usr/sbin/xtables-legacy-multi			iptables_exec_t
/var/lib/setroubleshoot/setroubleshoot_database.xml
/var/lib/setroubleshoot/*			setroubleshoot_var_lib_t
/usr/libexec/gsd-backlight-helper		xserver_exec_t
/usr/bin/pkla-check-authorization		policykit_auth_exec_t
/var/lib/mlocate/mlocate.db			locate_var_lib_t
/usr/lib/polkit-1/polkitd			policykit_exec_t
/usr/lib/systemd/systemd-logind			systemd_logind_exec_t
/usr/sbin/cupsd					cupsd_exec_t/cupsd_t
/etc/cups/subscriptions.conf
/usr/bin/gnome-keyring-daemon			gkeyringd_exec_t
/etc/udev/hwdb.bin				systemd_hwdb_etc_t
/usr/bin/podman					container_runtime_exec_t

```

avc msgs
```
home
type=AVC msg=audit(1563547435.107:1947): avc:  denied  { read open } for  pid=609 comm="precached/fanot" path=2F686F6D65652F666F6E74636F6 dev="mmcblk0p4" ino=1970836 scontext=system_u:system_r:precached_t:s0 tcontext=unconfined_u:object_r:cache_home_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547440.304:1951): avc:  denied  { read open } for  pid=609 comm="precached/fanot" path="/home/idnovic/.config/XXX/config.json" dev="mmcblk0p4" ino=1975038 scontext=system_u:system_r:precached_t:s0 tcontext=unconfined_u:object_r:config_home_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547435.108:1949): avc:  denied  { read open } for  pid=609 comm="precached/fanot" path="/home/idnovic/.bashrc" dev="mmcblk0p4" ino=1968495 scontext=system_u:system_r:precached_t:s0 tcontext=unconfined_u:object_r:user_home_t:s0 tclass=file permissive=1
tty-ask-password-agent
type=AVC msg=audit(1563547445.185:1976): avc:  denied  { getattr } for  pid=609 comm="precached" path="/usr/bin/systemd-tty-ask-password-agent" dev="mmcblk0p4" ino=3016080 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:systemd_passwd_agent_exec_t:s0 tclass=file permissive=1
utmp
type=AVC msg=audit(1563547444.663:1970): avc:  denied  { getattr } for  pid=609 comm="precached" path="/run/utmp" dev="tmpfs" ino=16621 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547444.663:1969): avc:  denied  { open } for  pid=609 comm="precached" path="/run/utmp" dev="tmpfs" ino=16621 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547444.663:1968): avc:  denied  { read } for  pid=609 comm="precached" name="utmp" dev="tmpfs" ino=16621 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=1
fprintd
type=AVC msg=audit(1563547442.86:1962): avc:  denied  { getattr } for  pid=609 comm="precached" path="/usr/libexec/fprintd" dev="mmcblk0p4" ino=3029809 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:fprintd_exec_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547442.82:1961): avc:  denied  { read } for  pid=609 comm="precached" name="exe" dev="proc" ino=80868 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:fprintd_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1563547442.82:1960): avc:  denied  { open } for  pid=609 comm="precached" path="/proc/3583/comm" dev="proc" ino=80867 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:fprintd_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547442.81:1959): avc:  denied  { read } for  pid=609 comm="precached" name="comm" dev="proc" ino=80867 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:fprintd_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547442.80:1958): avc:  denied  { search } for  pid=609 comm="precached" name="3583" dev="proc" ino=82116 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:fprintd_t:s0 tclass=dir permissive=1
geoclue
type=AVC msg=audit(1563547440.313:1957): avc:  denied  { getattr } for  pid=609 comm="precached/fanot" path="/usr/libexec/geoclue" dev="mmcblk0p4" ino=3033238 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:geoclue_exec_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547440.311:1956): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="exe" dev="proc" ino=45445 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:geoclue_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1563547440.311:1955): avc:  denied  { open } for  pid=609 comm="precached/fanot" path="/proc/1612/comm" dev="proc" ino=45444 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:geoclue_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547440.311:1954): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="comm" dev="proc" ino=45444 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:geoclue_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547440.310:1953): avc:  denied  { search } for  pid=609 comm="precached/fanot" name="1612" dev="proc" ino=40763 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:geoclue_t:s0 tclass=dir permissive=1
setroubleshoot
type=AVC msg=audit(1563547440.305:1952): avc:  denied  { read open } for  pid=609 comm="precached/fanot" path="/var/lib/setroubleshoot/setroubleshoot_database.xml" dev="mmcblk0p4" ino=2884386 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:setroubleshoot_var_lib_t:s0 tclass=file permissive=1
systemd
type=AVC msg=audit(1563547435.234:1950): avc:  denied  { getattr } for  pid=609 comm="precached/fanot" path="/usr/lib/systemd/systemd" dev="mmcblk0p4" ino=3022014 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:init_exec_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547435.106:1946): avc:  denied  { read open } for  pid=609 comm="precached/fanot" path="/usr/lib/systemd/user/gnome-terminal-server.service" dev="mmcblk0p4" ino=16514 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:systemd_unit_file_t:s0 tclass=file permissive=1
rpm
type=AVC msg=audit(1563547435.94:1944): avc:  denied  { open } for  pid=609 comm="precached/fanot" path="/var/lib/rpm/Packages" dev="mmcblk0p4" ino=2491146 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:rpm_var_lib_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547435.94:1943): avc:  denied  { read open } for  pid=609 comm="precached/fanot" path="/usr/bin/rpm" dev="mmcblk0p4" ino=3015920 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:rpm_exec_t:s0 tclass=file permissive=1
mlocate
type=AVC msg=audit(1563547435.44:1942): avc:  denied  { read open } for  pid=609 comm="precached/fanot" path="/var/lib/mlocate/mlocate.db" dev="mmcblk0p4" ino=2491963 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:locate_var_lib_t:s0 tclass=file permissive=1
chrony
type=AVC msg=audit(1563547424.693:1936): avc:  denied  { getattr } for  pid=609 comm="precached/fanot" path="/usr/sbin/chronyd" dev="mmcblk0p4" ino=3029785 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:chronyd_exec_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547424.691:1935): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="exe" dev="proc" ino=22757 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:chronyd_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1563547424.691:1934): avc:  denied  { open } for  pid=609 comm="precached/fanot" path="/proc/640/comm" dev="proc" ino=22756 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:chronyd_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547424.690:1933): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="comm" dev="proc" ino=22756 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:chronyd_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547424.689:1932): avc:  denied  { search } for  pid=609 comm="precached/fanot" name="640" dev="proc" ino=22755 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:chronyd_t:s0 tclass=dir permissive=1
auditd
type=AVC msg=audit(1563547409.604:1929): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="exe" dev="proc" ino=21854 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=lnk_file permissive=1
type=AVC msg=audit(1563547409.604:1928): avc:  denied  { open } for  pid=609 comm="precached/fanot" path="/proc/537/comm" dev="proc" ino=77775 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547409.603:1927): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="comm" dev="proc" ino=77775 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547409.603:1926): avc:  denied  { search } for  pid=609 comm="precached/fanot" name="537" dev="proc" ino=14958 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:auditd_t:s0 tclass=dir permissive=1
xdm/gdm
type=AVC msg=audit(1563547332.475:837): avc:  denied  { getattr } for  pid=609 comm="precached/fanot" path="/etc/gdm/custom.conf" dev="mmcblk0p4" ino=132485 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:xdm_etc_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547332.474:835): avc:  denied  { search } for  pid=609 comm="precached/fanot" name="gdm" dev="mmcblk0p4" ino=131143 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:xdm_etc_t:s0 tclass=dir permissive=1
type=AVC msg=audit(1563547332.468:834): avc:  denied  { open } for  pid=609 comm="precached/fanot" path="/proc/1121/comm" dev="proc" ino=34674 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tclass=file permissive=1
type=AVC msg=audit(1563547332.468:833): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="comm" dev="proc" ino=34674 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:xdm_t:s0-s0:c0.c1023 tclass=file permissive=1
NetworkManager
type=AVC msg=audit(1563547332.463:832): avc:  denied  { open } for  pid=609 comm="precached/fanot" path="/proc/1119/comm" dev="proc" ino=35718 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547332.463:831): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="comm" dev="proc" ino=35718 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=file permissive=1
type=AVC msg=audit(1563547332.463:830): avc:  denied  { search } for  pid=609 comm="precached/fanot" name="1119" dev="proc" ino=35389 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:NetworkManager_t:s0 tclass=dir permissive=1
```

**Comment by idnovic** [comment]
```
Raw-Audit-Meldungen
type=AVC msg=audit(1563477375.485:724): avc:  denied  { read } for  pid=5230 comm="precached" name="utmp" dev="tmpfs" ino=15090 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:initrc_var_run_t:s0 tclass=file permissive=1
```

Does precached require access to tmpfs? This is related to [question number 7](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513003417).

Is this swap related?

**Comment by idnovic** [comment]
to [question number 9](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513003417)
```
type=AVC msg=audit(1563547332.478:841): avc:  denied  { read } for  pid=609 comm="precached/fanot" name="exe" dev="proc" ino=35769 scontext=system_u:system_r:precached_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_dbusd_t:s0-s0:c0.c1023 tclass=lnk_file permissive=1
type=AVC msg=audit(1563547332.476:839): avc:  denied  { search } for  pid=609 comm="precached/fanot" name="1124" dev="proc" ino=35657 scontext=system_u:system_r:precached_t:s0 tcontext=unconfined_u:unconfined_r:unconfined_dbusd_t:s0-s0:c0.c1023 tclass=dir permissive=1
type=AVC msg=audit(1563547332.409:824): avc:  denied  { getattr } for  pid=609 comm="precached/fanot" path="/usr/bin/dbus-broker-launch" dev="mmcblk0p4" ino=3028254 scontext=system_u:system_r:precached_t:s0 tcontext=system_u:object_r:dbusd_exec_t:s0 tclass=file permissive=1
```

**Comment by idnovic** [comment]
Current state:
selinux policy in permissive mode, many avc notices, waiting on a proper working blacklist.
Currently precached slows the system down because selinux denies requests but precached keeps trying. This works while in permissive mode. In enforcing mode precached would have been killed by selinux for misbehaving :)

**Comment by idnovic** [comment]
```
iotracectl
rulesctl
```

are missing in the confinement, add them (note to myself)

EDIT: done in 1.3-1

**Comment by idnovic** [comment]
Find out whether the optional policy is needed: (precached.if)

```
	optional_policy(`
		systemd_passwd_agent_exec($1)
		systemd_read_fifo_file_passwd_run($1)
	') 
```

EDIT: commented out since version 1.3-1

**Comment by idnovic** [comment]
to [question number 10](https://github.com/X3n0m0rph59/precached/issues/22#issuecomment-513003417)

`type=AVC msg=audit(1563729491.891:1467): avc:  denied  { sys_ptrace } for  pid=598 comm="precached/fanot" capability=19  scontext=system_u:system_r:precached_t:s0 tcontext=system_u:system_r:precached_t:s0 tclass=cap_userns permissive=1`
